name: path_drawing
version: 0.4.1
description: >
  A flutter library to help with (Canvas) Path creation and manipulation
author: Dan Field <dfield@gmail.com>
homepage: https://github.com/dnfield/flutter_path_drawing

dependencies:
  vector_math: ">=2.0.6 <3.0.0" # google - https://github.com/google/vector_math.dart
  meta: ">=1.1.2 <2.0.0" # dart.dev
  path_parsing: # ^0.1.4 - TODO: Secure code review e8adaac7640ead6bc48dc57a1b1f9d3c1b799530 (0.1.4)
    git: 
      url: git://github.com/KomodoPlatform/dart_path_parsing.git
      ref: e8adaac7640ead6bc48dc57a1b1f9d3c1b799530
  flutter:
    sdk: flutter

dev_dependencies:
  path: ^1.5.1 # dart.dev
  test: "^1.3.4" # dart.dev
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

environment:
  sdk: ">=1.19.0 <3.0.0"
  flutter: ">=0.3.6 <2.0.0"
